import { Card, CardContent } from "@/components/ui/card";

interface ReceiptPreviewProps {
  receipt: {
    txHash: string;
    chain: string;
    fromAddress: string;
    toAddress: string;
    amount: string;
    token: string;
    usdValue: string;
    clientName: string;
    description: string;
    date: string;
  };
  businessName?: string;
}

export default function ReceiptPreview({ receipt, businessName }: ReceiptPreviewProps) {
  const formatDate = (dateStr: string) => {
    try {
      return new Date(dateStr).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });
    } catch {
      return dateStr;
    }
  };

  const formatAddress = (addr: string) => {
    if (addr.length < 12) return addr;
    return `${addr.slice(0, 6)}...${addr.slice(-4)}`;
  };

  return (
    <Card className="print:shadow-none print:border-0">
      <CardContent className="p-8">
        <div className="border-2 border-slate-200 p-6 rounded-lg bg-white">
          {/* Header */}
          <div className="border-b-2 border-slate-900 pb-4 mb-6">
            <div className="flex justify-between items-start">
              <div>
                <h2 className="text-2xl font-bold text-slate-900">
                  {businessName || "PAYMENT RECEIPT"}
                </h2>
                <p className="text-sm text-slate-500 mt-1">Generated by CryptoBooks</p>
              </div>
              <div className="text-right">
                <p className="text-sm font-semibold text-slate-700">RECEIPT</p>
                <p className="text-xs text-slate-400">
                  #{receipt.txHash.slice(0, 8)}
                </p>
              </div>
            </div>
          </div>

          {/* Details */}
          <div className="grid grid-cols-2 gap-6 mb-6">
            <div>
              <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">From</p>
              <p className="font-semibold text-slate-800">{receipt.clientName}</p>
              <p className="text-sm text-slate-500 font-mono">{formatAddress(receipt.fromAddress)}</p>
            </div>
            <div className="text-right">
              <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">To</p>
              <p className="font-semibold text-slate-800">{businessName || "Your Business"}</p>
              <p className="text-sm text-slate-500 font-mono">{formatAddress(receipt.toAddress)}</p>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-6 mb-6">
            <div>
              <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">Date</p>
              <p className="text-slate-800">{formatDate(receipt.date)}</p>
            </div>
            <div className="text-right">
              <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">Chain</p>
              <p className="text-slate-800 capitalize">{receipt.chain}</p>
            </div>
          </div>

          {/* Amount */}
          <div className="bg-slate-50 p-4 rounded-lg mb-6">
            <div className="flex justify-between items-center">
              <div>
                <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">Description</p>
                <p className="text-slate-800">{receipt.description}</p>
              </div>
              <div className="text-right">
                <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">Amount Paid</p>
                <p className="text-2xl font-bold text-slate-900">
                  {receipt.amount} {receipt.token}
                </p>
                <p className="text-sm text-slate-500">
                  ≈ ${receipt.usdValue} USD
                  {(receipt as any).usdIsEstimated && (
                    <span className="text-amber-600 ml-1">*</span>
                  )}
                </p>
                {(receipt as any).usdIsEstimated && (
                  <p className="text-xs text-amber-600 mt-1">
                    * USD value estimated. Use CoinGecko for accurate pricing.
                  </p>
                )}
              </div>
            </div>
          </div>

          {/* Transaction Info */}
          <div className="border-t border-slate-200 pt-4">
            <p className="text-xs text-slate-500 uppercase tracking-wide mb-2">Transaction Details</p>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p className="text-slate-500">Transaction Hash</p>
                <p className="font-mono text-slate-700 break-all">{receipt.txHash}</p>
              </div>
              <div>
                <p className="text-slate-500">Status</p>
                <p className="text-green-600 font-semibold">✓ Confirmed</p>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="mt-6 pt-4 border-t border-slate-200 text-center">
            <p className="text-xs text-slate-400">
              This receipt was generated from public blockchain data on {formatDate(new Date().toISOString())}.
            </p>
            <p className="text-xs text-slate-400">
              Verified via CryptoBooks • cryptobooks.app
            </p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
