import { Card, CardContent } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

interface Transaction {
  txHash: string;
  date: string;
  from: string;
  to: string;
  amount: string;
  token: string;
  usdValue: string;
  walletAddress: string;
}

interface StatementPreviewProps {
  transactions: Transaction[];
  totalIncome: string;
  startDate?: string;
  endDate?: string;
  walletCount: number;
}

export default function StatementPreview({
  transactions,
  totalIncome,
  startDate,
  endDate,
  walletCount,
}: StatementPreviewProps) {
  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  };

  const formatAddress = (addr: string) => {
    if (addr.length < 12) return addr;
    return `${addr.slice(0, 6)}...${addr.slice(-4)}`;
  };

  const periodText = () => {
    if (startDate && endDate) {
      return `${formatDate(startDate)} - ${formatDate(endDate)}`;
    }
    return "All time";
  };

  // Calculate running balance (reverse order for running total)
  const sortedTxns = [...transactions].sort(
    (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
  );

  let runningBalance = 0;
  const txnsWithBalance = sortedTxns.map((t) => {
    runningBalance += parseFloat(t.usdValue);
    return { ...t, balance: runningBalance.toFixed(2) };
  });

  // Reverse back to show newest first
  const displayTxns = [...txnsWithBalance].reverse();

  return (
    <Card className="print:shadow-none print:border-0">
      <CardContent className="p-8">
        <div className="border-2 border-slate-200 p-6 rounded-lg bg-white space-y-6">
          {/* Header */}
          <div className="border-b-2 border-slate-900 pb-4">
            <div className="flex justify-between items-start">
              <div>
                <h2 className="text-2xl font-bold text-slate-900">
                  TRANSACTION STATEMENT
                </h2>
                <p className="text-sm text-slate-500 mt-1">
                  Generated by CryptoBooks
                </p>
              </div>
              <div className="text-right">
                <p className="text-sm font-semibold text-slate-700">
                  STATEMENT
                </p>
                <p className="text-xs text-slate-400">
                  {walletCount} wallet{walletCount > 1 ? 's' : ''}
                </p>
              </div>
            </div>
          </div>

          {/* Period & Summary */}
          <div className="grid grid-cols-2 gap-6">
            <div>
              <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">
                Period
              </p>
              <p className="text-slate-800 font-medium">{periodText()}</p>
            </div>
            <div className="text-right">
              <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">
                Total Income
              </p>
              <p className="text-2xl font-bold text-slate-900">
                ${parseFloat(totalIncome).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </p>
            </div>
          </div>

          {/* Transactions Table */}
          <div className="border rounded-lg overflow-hidden">
            <Table>
              <TableHeader>
                <TableRow className="bg-slate-50">
                  <TableHead className="text-xs">Date</TableHead>
                  <TableHead className="text-xs">From</TableHead>
                  <TableHead className="text-xs">Token</TableHead>
                  <TableHead className="text-xs text-right">Amount</TableHead>
                  <TableHead className="text-xs text-right">USD Value</TableHead>
                  <TableHead className="text-xs text-right">Balance</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {displayTxns.length === 0 ? (
                  <TableRow>
                    <TableCell
                      colSpan={6}
                      className="text-center text-slate-500 py-8"
                    >
                      No transactions found for this period.
                    </TableCell>
                  </TableRow>
                ) : (
                  displayTxns.map((txn, index) => (
                    <TableRow key={txn.txHash + index}>
                      <TableCell className="text-sm">
                        {formatDate(txn.date)}
                      </TableCell>
                      <TableCell className="text-sm font-mono">
                        {formatAddress(txn.from)}
                      </TableCell>
                      <TableCell className="text-sm">
                        <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-50 text-blue-700">
                          {txn.token}
                        </span>
                      </TableCell>
                      <TableCell className="text-sm text-right font-mono">
                        {txn.amount}
                      </TableCell>
                      <TableCell className="text-sm text-right font-mono">
                        ${parseFloat(txn.usdValue).toFixed(2)}
                      </TableCell>
                      <TableCell className="text-sm text-right font-mono font-medium">
                        ${parseFloat(txn.balance).toFixed(2)}
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>

          {/* Footer Summary */}
          <div className="bg-slate-50 p-4 rounded-lg">
            <div className="flex justify-between items-center">
              <div>
                <p className="text-xs text-slate-500 uppercase tracking-wide">
                  Transactions
                </p>
                <p className="text-lg font-semibold">
                  {transactions.length}
                </p>
              </div>
              <div className="text-right">
                <p className="text-xs text-slate-500 uppercase tracking-wide">
                  Closing Balance
                </p>
                <p className="text-lg font-semibold">
                  ${parseFloat(totalIncome).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                </p>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="mt-6 pt-4 border-t border-slate-200 text-center">
            <p className="text-xs text-slate-400">
              This statement was generated from public blockchain data on{' '}
              {new Date().toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'long',
                day: 'numeric',
              })}
              .
            </p>
            <p className="text-xs text-slate-400">
              Verified via CryptoBooks • cryptobooks.app
            </p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
