import { Card, CardContent } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

interface Transaction {
  txHash: string;
  date: string;
  from: string;
  to: string;
  amount: string;
  token: string;
  usdValue: string | null;
  usdIsEstimated?: boolean;
  priceSource?: string;
  walletAddress: string;
}

interface StatementPreviewProps {
  transactions: Transaction[];
  totalIncome: string;
  startDate?: string;
  endDate?: string;
  walletCount: number;
}

export default function StatementPreview({
  transactions,
  totalIncome,
  startDate,
  endDate,
  walletCount,
}: StatementPreviewProps) {
  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  };

  const formatAddress = (addr: string) => {
    if (addr.length < 12) return addr;
    return `${addr.slice(0, 6)}...${addr.slice(-4)}`;
  };

  const periodText = () => {
    if (startDate && endDate) {
      return `${formatDate(startDate)} - ${formatDate(endDate)}`;
    }
    return "All time";
  };

  const formatUsdValue = (t: Transaction) => {
    if (t.usdValue === null) {
      return <span className="text-slate-300">—</span>;
    }
    
    if (t.priceSource === "stablecoin") {
      return <span className="text-green-700">${parseFloat(t.usdValue).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>;
    }
    
    if (t.usdIsEstimated) {
      return (
        <span className="text-amber-700" title="Estimated via CoinGecko historical price">
          ~${parseFloat(t.usdValue).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
        </span>
      );
    }
    
    return <span>${parseFloat(t.usdValue).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>;
  };

  const getTokenBadgeClass = (t: Transaction) => {
    if (t.priceSource === "stablecoin") {
      return "inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-green-50 text-green-700";
    }
    if (t.usdValue !== null) {
      return "inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-50 text-blue-700";
    }
    return "inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-amber-50 text-amber-700";
  };

  // Calculate running balance (only sum transactions with USD values)
  const sortedTxns = [...transactions].sort(
    (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
  );

  let runningBalance = 0;
  const txnsWithBalance = sortedTxns.map((t) => {
    if (t.usdValue !== null) {
      runningBalance += parseFloat(t.usdValue);
    }
    return { ...t, balance: runningBalance.toFixed(2), hasBalance: t.usdValue !== null };
  });

  // Reverse back to show newest first
  const displayTxns = [...txnsWithBalance].reverse();
  
  const pricedCount = transactions.filter(t => t.usdValue !== null).length;
  const estimatedCount = transactions.filter(t => t.usdIsEstimated).length;
  const stablecoinCount = transactions.filter(t => t.priceSource === "stablecoin").length;
  const missingCount = transactions.length - pricedCount;

  return (
    <Card className="print:shadow-none print:border-0">
      <CardContent className="p-8">
        <div className="border-2 border-slate-200 p-6 rounded-lg bg-white space-y-6">
          {/* Header */}
          <div className="border-b-2 border-slate-900 pb-4">
            <div className="flex justify-between items-start">
              <div>
                <h2 className="text-2xl font-bold text-slate-900">
                  TRANSACTION STATEMENT
                </h2>
                <p className="text-sm text-slate-500 mt-1">
                  Generated by CryptoBooks
                </p>
              </div>
              <div className="text-right">
                <p className="text-sm font-semibold text-slate-700">
                  STATEMENT
                </p>
                <p className="text-xs text-slate-400">
                  {walletCount} wallet{walletCount > 1 ? 's' : ''}
                </p>
              </div>
            </div>
          </div>

          {/* Period & Summary */}
          <div className="grid grid-cols-2 gap-6">
            <div>
              <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">
                Period
              </p>
              <p className="text-slate-800 font-medium">{periodText()}</p>
            </div>
            <div className="text-right">
              <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">
                Total Income
              </p>
              <p className="text-2xl font-bold text-slate-900">
                ${parseFloat(totalIncome).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </p>
            </div>
          </div>

          {/* Price Legend */}
          <div className="flex flex-wrap gap-4 text-xs text-slate-500 bg-slate-50 p-3 rounded-lg">
            <div className="flex items-center gap-1.5">
              <span className="inline-block w-2 h-2 rounded-full bg-green-500" />
              {stablecoinCount} stablecoin (exact)
            </div>
            {estimatedCount > 0 && (
              <div className="flex items-center gap-1.5">
                <span className="inline-block w-2 h-2 rounded-full bg-blue-500" />
                {estimatedCount} estimated via CoinGecko
              </div>
            )}
            {missingCount > 0 && (
              <div className="flex items-center gap-1.5">
                <span className="inline-block w-2 h-2 rounded-full bg-amber-500" />
                {missingCount} no price data (unavailable)
              </div>
            )}
          </div>

          {/* Transactions Table */}
          <div className="border rounded-lg overflow-hidden">
            <Table>
              <TableHeader>
                <TableRow className="bg-slate-50">
                  <TableHead className="text-xs">Date</TableHead>
                  <TableHead className="text-xs">From</TableHead>
                  <TableHead className="text-xs">Token</TableHead>
                  <TableHead className="text-xs text-right">Amount</TableHead>
                  <TableHead className="text-xs text-right">USD Value</TableHead>
                  <TableHead className="text-xs text-right">Balance</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {displayTxns.length === 0 ? (
                  <TableRow>
                    <TableCell
                      colSpan={6}
                      className="text-center text-slate-500 py-8"
                    >
                      No transactions found for this period.
                    </TableCell>
                  </TableRow>
                ) : (
                  displayTxns.map((txn, index) => (
                    <TableRow key={`${txn.txHash}-${txn.date}-${index}`}>
                      <TableCell className="text-sm">
                        {formatDate(txn.date)}
                      </TableCell>
                      <TableCell className="text-sm font-mono">
                        {formatAddress(txn.from)}
                      </TableCell>
                      <TableCell className="text-sm">
                        <span className={getTokenBadgeClass(txn)}>
                          {txn.token}
                        </span>
                      </TableCell>
                      <TableCell className="text-sm text-right font-mono">
                        {parseFloat(txn.amount).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 6 })}
                      </TableCell>
                      <TableCell className="text-sm text-right font-mono">
                        {formatUsdValue(txn)}
                      </TableCell>
                      <TableCell className="text-sm text-right font-mono font-medium">
                        {txn.hasBalance ? (
                          <span>${parseFloat(txn.balance).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
                        ) : (
                          <span className="text-slate-300">—</span>
                        )}
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>

          {/* Footer Summary */}
          <div className="bg-slate-50 p-4 rounded-lg">
            <div className="flex justify-between items-center">
              <div>
                <p className="text-xs text-slate-500 uppercase tracking-wide">
                  Transactions
                </p>
                <p className="text-lg font-semibold">
                  {transactions.length}
                </p>
              </div>
              <div className="text-right">
                <p className="text-xs text-slate-500 uppercase tracking-wide">
                  Closing Balance
                </p>
                <p className="text-lg font-semibold">
                  ${parseFloat(totalIncome).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                </p>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="mt-6 pt-4 border-t border-slate-200 text-center">
            <p className="text-xs text-slate-400">
              This statement was generated from public blockchain data on{' '}
              {new Date().toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'long',
                day: 'numeric',
              })}
              .
            </p>
            <p className="text-xs text-slate-400">
              USD values for non-stablecoins are estimated via CoinGecko historical prices.
              Prices older than 1 year may be unavailable on the free tier.
            </p>
            <p className="text-xs text-slate-400 mt-1">
              Verified via CryptoBooks • cryptobooks.app
            </p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
